# markdown_report.py
"""
Markdown report generator.
Creates professional pentest-style reports.
"""

from tabnanny import check
from typing import List
from datetime import datetime
from checks.base_check import Finding
from core.analyzer import Analyzer
from core.scorer import Scorer
from core.attack_path import AttackPathBuilder
from utils.helpers import SystemHelpers


class MarkdownReport:
    """Generates Markdown report from findings."""
    
    def __init__(self, findings: List[Finding]):
        """
        Initialize Markdown report generator.
        
        Args:
            findings: List of findings
        """
        self.findings = findings
        self.analyzer = Analyzer(findings)
        self.scorer = Scorer(findings)
        self.path_builder = AttackPathBuilder(findings)
    
    def generate(self, filename: str = None) -> str:
        """
        Generate Markdown report.
        
        Args:
            filename: Optional filename to write to
            
        Returns:
            Markdown report as string
        """
        report_lines = []
        
        # Header
        report_lines.extend([
            "# PrivAudit - Linux Privilege Escalation Audit Report",
            "",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Hostname:** {self._get_hostname()}",
            f"**User:** {SystemHelpers.get_current_user()}",
            f"**Kernel:** {self._get_kernel_version()}",
            "",
            "---",
            ""
        ])
        
        # Executive Summary
        report_lines.extend(self._generate_summary())
        
        # Risk Assessment
        report_lines.extend(self._generate_risk_assessment())
        
        # Attack Paths
        report_lines.extend(self._generate_attack_paths())
        
        # Quick Wins
        report_lines.extend(self._generate_quick_wins())
        
        # Detailed Findings
        report_lines.extend(self._generate_detailed_findings())
        
        # Recommendations
        report_lines.extend(self._generate_recommendations())
        
        # Footer
        report_lines.extend([
            "",
            "---",
            "",
            f"*Report generated by PrivAudit v1.0.0*"
        ])
        
        report = "\n".join(report_lines)
        
        if filename:
            with open(filename, 'w') as f:
                f.write(report)
        
        return report
    
    def _generate_summary(self) -> List[str]:
        """Generate executive summary section."""
        summary = self.analyzer.get_summary()
        risk_level = self.scorer.get_risk_level()
        
        return [
            "## Executive Summary",
            "",
            f"PrivAudit identified **{summary['total_findings']}** potential privilege escalation vectors on the target system.",
            "",
            f"### Key Metrics",
            "",
            "| Severity | Count |",
            "|----------|-------|",
            f"| Critical | {summary['critical']} |",
            f"| High | {summary['high']} |",
            f"| Medium | {summary['medium']} |",
            f"| Low | {summary['low']} |",
            f"| Info | {summary['info']} |",
            "",
            f"**Overall Risk Level:** **{risk_level}**",
            "",
            f"**Total Risk Score:** **{self.scorer.get_total_risk_score():.1f}**",
            "",
            "---",
            ""
        ]
    
    def _generate_risk_assessment(self) -> List[str]:
        """Generate risk assessment section."""
        top_risks = self.scorer.get_top_risks(5)
        
        lines = [
            "## Risk Assessment",
            "",
            "### Top 5 Highest Risk Findings",
            "",
            "| Rank | Finding | Score | Severity |",
            "|------|---------|-------|----------|",
        ]
        
        for i, risk in enumerate(top_risks, 1):
            finding = risk['finding']
            lines.append(f"| {i} | {finding.title} | {risk['final_score']:.1f} | {finding.severity.name} |")
        
        lines.extend(["", "---", ""])
        return lines
    
    def _generate_attack_paths(self) -> List[str]:
        """Generate attack paths section."""
        paths = self.path_builder.get_paths()
        
        if not paths:
            return ["## Attack Paths", "", "No clear attack paths identified.", "", "---", ""]
        
        lines = [
            "## Attack Paths",
            "",
            "The following attack paths represent the most likely privilege escalation vectors:",
            ""
        ]
        
        for i, path in enumerate(paths[:3], 1):
            lines.extend([
                f"### {i}. {path['name']}",
                "",
                f"- **Likelihood:** {path['likelihood']:.1f}%",
                f"- **Impact:** {path['impact']}",
                f"- **Steps Required:** {path['steps']}",
                "",
                "#### Findings in this path:",
                ""
            ])
            
            for finding in path['findings']:
                lines.extend([
                    f"- **{finding.title}**",
                    f"  - {finding.description}",
                    f"  - Exploit: `{finding.exploit_suggestion or 'Research required'}`",
                    ""
                ])
        
        lines.extend(["---", ""])
        return lines
    
    def _generate_quick_wins(self) -> List[str]:
        """Generate quick wins section."""
        quick_wins = self.path_builder.get_quick_wins()
        
        if not quick_wins:
            return []
        
        lines = [
            "## Quick Wins",
            "",
            "These findings represent the easiest paths to privilege escalation:",
            ""
        ]
        
        for i, finding in enumerate(quick_wins, 1):
            lines.extend([
                f"### {i}. {finding.title}",
                "",
                f"**Severity:** {finding.severity.name}",
                "",
                f"**Description:** {finding.description}",
                "",
                f"**Exploit Command:**",
                f"```bash",
                f"{finding.exploit_suggestion or 'See exploit database'}",
                f"```",
                "",
                f"**Remediation:** {finding.remediation or 'Review and secure configuration'}",
                ""
            ])
        
        lines.extend(["---", ""])
        return lines
    
    def _generate_detailed_findings(self) -> List[str]:
        """Generate detailed findings section."""
        lines = [
            "## Detailed Findings",
            ""
        ]
        
        # Group by severity
        for severity in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
            findings = self.analyzer.by_severity.get(getattr(checks.base_check.Severity, severity), []) # type: ignore
            if findings:
                lines.append(f"### {severity} Findings ({len(findings)})")
                lines.append("")
                
                for finding in findings:
                    lines.extend([
                        f"#### {finding.title}",
                        "",
                        f"**Description:** {finding.description}",
                        "",
                        f"**Metadata:**",
                        "```json",
                        f"{self._format_metadata(finding.metadata)}",
                        "```",
                        ""
                    ])
                    
                    if finding.exploit_suggestion:
                        lines.extend([
                            f"**Exploit:**",
                            f"```bash",
                            f"{finding.exploit_suggestion}",
                            f"```",
                            ""
                        ])
                    
                    if finding.remediation:
                        lines.extend([
                            f"**Remediation:**",
                            f"```bash",
                            f"{finding.remediation}",
                            f"```",
                            ""
                        ])
        
        lines.append("---")
        lines.append("")
        return lines
    
    def _generate_recommendations(self) -> List[str]:
        """Generate recommendations section."""
        return [
            "## Recommendations",
            "",
            "Based on the audit findings, the following actions are recommended:",
            "",
            "### Immediate Actions",
            "",
            "1. **Patch Critical Issues**: Address all CRITICAL severity findings immediately",
            "2. **Review Sudo Access**: Remove unnecessary sudo privileges",
            "3. **Secure SUID Binaries**: Remove SUID bit from unnecessary binaries",
            "4. **Restrict Docker Access**: Remove users from docker group if not required",
            "",
            "### Medium-Term Actions",
            "",
            "1. **Update Kernel**: Apply latest kernel security patches",
            "2. **Implement MAC**: Enable AppArmor or SELinux",
            "3. **Audit Cron Jobs**: Review and secure all cron configurations",
            "4. **Monitor File Permissions**: Implement file integrity monitoring",
            "",
            "### Long-Term Actions",
            "",
            "1. **Principle of Least Privilege**: Review all user permissions",
            "2. **Regular Audits**: Schedule regular privilege escalation audits",
            "3. **Security Training**: Train administrators on secure configurations",
            "4. **Incident Response**: Develop procedures for detected escalations",
            ""
        ]
    
    def _format_metadata(self, metadata: dict) -> str:
        """Format metadata for markdown."""
        import json
        return json.dumps(metadata, indent=2)
    
    def _get_hostname(self) -> str:
        """Get system hostname."""
        import socket
        return socket.gethostname()
    
    def _get_kernel_version(self) -> str:
        """Get kernel version."""
        try:
            import platform
            return platform.release()
        except:
            return 'Unknown'